"""add threat_score to indicators

Revision ID: 03f2d50e3da9
Revises: 3538131a33b6
Create Date: 2026-08-06 17:55:21.340327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03f2d50e3da9'
down_revision: Union[str, Sequence[str], None] = '3538131a33b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "indicators",
        sa.Column(
            "threat_score",
            sa.Integer(),
            nullable=False,
            server_default="10",
        ),
    )

    # Optional: remove the database default after existing rows are populated.
    op.alter_column(
        "indicators",
        "threat_score",
        server_default=None,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('indicators', 'threat_score')
    # ### end Alembic commands ###
