"""create indicators table

Revision ID: 3538131a33b6
Revises: 9e2c4cc94571
Create Date: 2026-08-05 13:25:09.715139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3538131a33b6'
down_revision: Union[str, Sequence[str], None] = '9e2c4cc94571'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicator_type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_index(op.f('ix_indicators_id'), 'indicators', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_indicators_id'), table_name='indicators')
    op.drop_table('indicators')
    # ### end Alembic commands ###
