"""add reputation_score to indicators

Revision ID: a1357699d25f
Revises: 03f2d50e3da9
Create Date: 2026-08-07 11:01:56.339372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1357699d25f'
down_revision: Union[str, Sequence[str], None] = '03f2d50e3da9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "indicators",
        sa.Column(
            "reputation_score",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
    )

    # Remove the temporary default after existing rows are populated.
    op.alter_column(
        "indicators",
        "reputation_score",
        server_default=None,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('indicators', 'reputation_score')
    # ### end Alembic commands ###
