"""add incident resolution lifecycle

Revision ID: ce39d80c1d28
Revises: af116003fb6e
Create Date: 2026-08-30 18:02:03.836052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce39d80c1d28'
down_revision: Union[str, Sequence[str], None] = 'af116003fb6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    resolution_type_enum = sa.Enum(
        'TRUE_POSITIVE',
        'FALSE_POSITIVE',
        'BENIGN',
        'DUPLICATE',
        name='incidentresolutiontype',
    )

    resolution_type_enum.create(
        op.get_bind(),
        checkfirst=True,
    )

    op.add_column(
        'incidents',
        sa.Column(
            'resolution_type',
            resolution_type_enum,
            nullable=True,
        ),
    )
    op.add_column('incidents', sa.Column('resolution_summary', sa.Text(), nullable=True))
    op.add_column('incidents', sa.Column('resolved_by', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_incidents_resolution_type'), 'incidents', ['resolution_type'], unique=False)
    op.create_index(op.f('ix_incidents_resolved_by'), 'incidents', ['resolved_by'], unique=False)
    op.create_foreign_key(None, 'incidents', 'users', ['resolved_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    op.drop_index(op.f('ix_incidents_resolved_by'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_resolution_type'), table_name='incidents')
    op.drop_column('incidents', 'resolved_by')
    op.drop_column('incidents', 'resolution_summary')
    op.drop_column('incidents', 'resolution_type')

    # PostgreSQL native enum types survive column removal,
    # so remove the enum explicitly during downgrade.
    sa.Enum(
        name='incidentresolutiontype'
    ).drop(
        op.get_bind(),
        checkfirst=True,
    )
    # ### end Alembic commands ###
